version: "3.4"
services:
  api:
    image: fast_api
    container_name: ml_api223
    build:
      context: ./app
      target: build
    ports:
      - "80:5000"
    
    depends_on:
      - redis
      - model
    volumes:
      - ./feedback:/src/feedback
      - ./uploads:/src/static/uploads

  redis:
    image: redis:6.2.6
    # ports:
    #  - "6379:6379"

  model:
    image: ml_service
    build:
      context: ./model
      target: build
    depends_on:
      - redis
    volumes:
      - ./uploads:/src/uploads
      - ./feedback:/src/feedback
